// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: internal/transport/grpc/auth.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequiredRoles []string               `protobuf:"bytes,2,rep,name=required_roles,json=requiredRoles,proto3" json:"required_roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_internal_transport_grpc_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckAccessRequest) GetRequiredRoles() []string {
	if x != nil {
		return x.RequiredRoles
	}
	return nil
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_internal_transport_grpc_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_transport_grpc_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_internal_transport_grpc_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_transport_grpc_auth_proto protoreflect.FileDescriptor

const file_internal_transport_grpc_auth_proto_rawDesc = "" +
	"\n" +
	"\"internal/transport/grpc/auth.proto\x12\x04auth\"Q\n" +
	"\x12CheckAccessRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0erequired_roles\x18\x02 \x03(\tR\rrequiredRoles\"^\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2Q\n" +
	"\vAuthService\x12B\n" +
	"\vCheckAccess\x12\x18.auth.CheckAccessRequest\x1a\x19.auth.CheckAccessResponseB\x19Z\x17internal/transport/grpcb\x06proto3"

var (
	file_internal_transport_grpc_auth_proto_rawDescOnce sync.Once
	file_internal_transport_grpc_auth_proto_rawDescData []byte
)

func file_internal_transport_grpc_auth_proto_rawDescGZIP() []byte {
	file_internal_transport_grpc_auth_proto_rawDescOnce.Do(func() {
		file_internal_transport_grpc_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_auth_proto_rawDesc), len(file_internal_transport_grpc_auth_proto_rawDesc)))
	})
	return file_internal_transport_grpc_auth_proto_rawDescData
}

var file_internal_transport_grpc_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_transport_grpc_auth_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),  // 0: auth.CheckAccessRequest
	(*CheckAccessResponse)(nil), // 1: auth.CheckAccessResponse
}
var file_internal_transport_grpc_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.CheckAccess:input_type -> auth.CheckAccessRequest
	1, // 1: auth.AuthService.CheckAccess:output_type -> auth.CheckAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_transport_grpc_auth_proto_init() }
func file_internal_transport_grpc_auth_proto_init() {
	if File_internal_transport_grpc_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_transport_grpc_auth_proto_rawDesc), len(file_internal_transport_grpc_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_transport_grpc_auth_proto_goTypes,
		DependencyIndexes: file_internal_transport_grpc_auth_proto_depIdxs,
		MessageInfos:      file_internal_transport_grpc_auth_proto_msgTypes,
	}.Build()
	File_internal_transport_grpc_auth_proto = out.File
	file_internal_transport_grpc_auth_proto_goTypes = nil
	file_internal_transport_grpc_auth_proto_depIdxs = nil
}
